# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-11-12 15:36
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('guruquiz', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='source_videos',
            field=models.ManyToManyField(through='guruquiz.ProductToVideo', to='guruquiz.Video'),
        ),
        migrations.AddField(
            model_name='quiz',
            name='respondents',
            field=models.ManyToManyField(through='guruquiz.BloggerToQuiz', to='guruquiz.Blogger'),
        ),
        migrations.AlterField(
            model_name='producttovideo',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='guruquiz.Product'),
        ),
    ]
